# Generated by Django 4.2.27 on 2026-03-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScheduleSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_start_hour", models.PositiveSmallIntegerField(default=9)),
                ("work_end_hour", models.PositiveSmallIntegerField(default=17)),
                ("focus_block_max_hours", models.FloatField(default=2.0)),
                ("break_interval_minutes", models.PositiveIntegerField(default=90)),
                ("lunch_duration_minutes", models.PositiveIntegerField(default=60)),
                ("lunch_hour", models.PositiveSmallIntegerField(default=13)),
            ],
            options={
                "verbose_name_plural": "Schedule settings",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("duration_minutes", models.PositiveIntegerField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("focus", "Focus"),
                            ("meeting", "Meeting"),
                            ("admin", "Admin"),
                            ("creative", "Creative"),
                            ("learning", "Learning"),
                        ],
                        default="focus",
                        max_length=20,
                    ),
                ),
                ("deadline", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
