# Generated by Django 4.2.27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_whatsapp_notification_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappnotificationstate",
            name="last_mqtt_ok",
            field=models.BooleanField(blank=True, help_text="True=last publish succeeded, False=failed, null=never tried", null=True),
        ),
        migrations.AddField(
            model_name="whatsappnotificationstate",
            name="last_mqtt_checked_at",
            field=models.DateTimeField(blank=True, help_text="When we last attempted MQTT publish", null=True),
        ),
    ]
